export const menuItemsData = [
  {
    id: 1,
    name: 'Pav Bhaji',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 100,
    img: '/images/pavbhaji.png',
  },
  {
    id: 2,
    name: 'Samosa',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 14,
    img: '/images/samosa.png',
  },
  {
    id: 3,
    name: 'French Fries',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 40,
    img: '/images/fries.png',
  },
  {
    id: 4,
    name: 'Fried Rice',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 120,
    img: '/images/friedrice.png',
  },
  {
    id: 5,
    name: ' Instant Noodles',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 30,
    img: '/images/maggi.png',
  },
  {
    id: 6,
    name: 'Cheese Grilled Sandwich',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 50,
    img: '/images/sand.png',
  },
  {
    id: 7,
    name: 'Idli',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 20,
    img: '/images/idli1.png',
  },
  {
    id: 8,
    name: 'Dahi Puri',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 45,
    img: '/images/dahi.png',
  },
  {
    id: 9,
    name: 'Masala Dosa',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 50,
    img: '/images/dosa.png',
  },
  {
    id: 10,
    name: 'Indian Thali',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 200,
    img: '/images/thali.png',
  },
  {
    id: 11,
    name: 'Khaman Dhokla',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 30,
    img: '/images/dhokla.png',
  },
  {
    id: 12,
    name: 'Diet Salad',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 150,
    img: '/images/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
  },
  {
    id: 13,
    name: 'Jalebi per 100g',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 20,
    img: '/images/jalebi.png',
  },
  {
    id: 14,
    name: 'Cheese Pizza',
    info: 'spicey with garlic and then deep fried to crispy perfection',
    price: 150,
    img: '/images/pizza.png',
  },
];
